title: Diego Barros
description: Cayman Blog Theme is a clean, responsive blogging theme for Jekyll and Gitlab/GitHub Pages.

baseurl: "/inicio" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://lorepirri.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: oidiegobarros
image: /thumbnail-jumbo.png
github:
  username: oidiegobarros
  url: https://github.com/oidiegobarros
linkedin:
  username: oidiegobarros
  url: https://www.linkedin.com/in/oidiegobarros/?_l=pt_BR

twitter:
  username: lorepirri


plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
